/**
 * Dial channel adapter for NanoClaw v2.
 *
 * Dial (https://getdial.ai) gives an agent a real phone number — SMS and
 * AI-handled voice calls. Native adapter (no Chat SDK bridge).
 *
 *   - Outbound SMS via the official `@getdial/sdk` (`DialClient.sendMessage`).
 *   - Inbound via Dial's documented CLI command-target
 *     (docs.getdial.ai/integrations/agent-clients/nanoclaw): the `dial listen`
 *     daemon runs a spool handler per event; the adapter watches the spool
 *     directory and routes each event.
 *
 * PUBLIC-LINE MODEL. The Dial number is one room shared by many people (a
 * messaging group whose platform_id is the number itself), and each remote
 * correspondent is a THREAD inside it (threadId = their E.164). One wiring +
 * `unknown_sender_policy: 'public'` therefore lets anyone text/call the number
 * and reach the agent with no per-sender approval, while replies still route
 * to the right person via their thread. A pairing code (see dial-pairing.ts)
 * only proves the operator controls a phone: the interceptor records the sender
 * as a pairing CANDIDATE before the message reaches an agent, and nothing more.
 * The owner role is granted solely by the operator-run setup wizard
 * (setup/pair-dial.ts) — an inbound SMS is never trusted to grant itself a role.
 *
 * Unlike other channels one platform_id serves many correspondents, so the
 * line must be a group: per-thread sessions are what keep them apart.
 *
 * Credentials come from Dial's auth file (written by `dial onboard`). If
 * there's no key the factory returns null and the channel is skipped.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';

import { DialClient } from '@getdial/sdk';

import type { ChannelAdapter, ChannelDefaults, ChannelSetup, InboundMessage, OutboundMessage } from './adapter.js';
import { registerChannelAdapter } from './channel-registry.js';
import { tryConsume } from './dial-pairing.js';
import { DATA_DIR } from '../config.js';
import { getMessagingGroupsByChannel, updateMessagingGroup } from '../db/messaging-groups.js';
import { readEnvFile } from '../env.js';
import { log } from '../log.js';
import type { MessagingGroup, UnknownSenderPolicy } from '../types.js';
import { getOwners } from '../modules/permissions/db/user-roles.js';
import { upsertUser } from '../modules/permissions/db/users.js';

/**
 * Record a matched pairing sender as a candidate for ownership. This does NOT
 * grant any role: an inbound SMS is not a trusted authority. The operator-run
 * setup wizard (setup/pair-dial.ts) is the only path that grants owner, after
 * it observes the same consumed pairing. Returns the recorded user id.
 */
export function recordPairingCandidate(fromNumber: string, at: string = new Date().toISOString()): string {
  const userId = `dial:${fromNumber}`;
  upsertUser({ id: userId, kind: 'dial', display_name: null, created_at: at });
  return userId;
}

/** Longest SMS body sent in one shot; longer text is chunked. */
const MAX_CHUNK = 1500;

/** Dedup window — the listen daemon retries a failed handler invocation once. */
const DEDUP_TTL_MS = 5 * 60_000;

/** Dial listen-daemon event envelope (the subset we consume). */
interface DialEventEnvelope {
  id?: string;
  type?: string;
  createdAt?: string;
  data?: Record<string, unknown>;
}

interface DialConfig {
  apiKey: string;
  /** The account's Dial number (E.164). Used as the shared line's platform_id. */
  fromNumber: string;
  cliPath: string;
}

function chunkText(text: string, limit: number): string[] {
  const chunks: string[] = [];
  let remaining = text;
  while (remaining.length > 0) {
    if (remaining.length <= limit) {
      chunks.push(remaining);
      break;
    }
    let splitAt = remaining.lastIndexOf('\n', limit);
    if (splitAt <= 0) splitAt = limit;
    chunks.push(remaining.slice(0, splitAt));
    remaining = remaining.slice(splitAt).replace(/^\n/, '');
  }
  return chunks;
}

/**
 * The handler script Dial's listen daemon runs per event: it spools the event
 * JSON (passed as the final positional argument) into a directory the adapter
 * watches, written atomically (temp + rename). Runs with a clean env (PATH +
 * HOME only), so the spool dir is baked in as an absolute path.
 */
function handlerScript(spoolDir: string): string {
  return `#!/usr/bin/env bash
# Auto-generated by NanoClaw's Dial channel adapter (src/channels/dial.ts).
# Dial CLI command target: https://docs.getdial.ai/integrations/methods/cli-command-target
set -euo pipefail
[ "$#" -eq 0 ] && exit 0
spool=${JSON.stringify(spoolDir)}
mkdir -p "$spool"
event="\${!#}"   # value of the last positional parameter = the event JSON
tmp="$spool/.tmp.$$.\${RANDOM}"
printf '%s' "$event" > "$tmp"
mv -f "$tmp" "$spool/$(date +%s).$$.\${RANDOM}.json"
exit 0
`;
}

/**
 * `threads: true` gives each correspondent their own thread/session so replies
 * route back correctly. `strict` is the safe default for creation — the
 * operator picks owner-only or public during setup and the adapter reconciles
 * the line to that choice (see inboundPolicy), so a line is never briefly
 * open to everyone before the choice is applied.
 */
const DIAL_DEFAULTS: ChannelDefaults = {
  dm: { engageMode: 'pattern', engagePattern: '.', threads: true, unknownSenderPolicy: 'strict' },
  group: { engageMode: 'pattern', engagePattern: '.', threads: true, unknownSenderPolicy: 'strict' },
  mentions: 'dm-only',
};

export function createDialAdapter(config: DialConfig): ChannelAdapter {
  const client = new DialClient({ apiKey: config.apiKey });
  const spoolDir = path.join(DATA_DIR, 'dial', 'inbound');
  const handlerPath = path.join(DATA_DIR, 'dial', 'handle-dial-event.sh');
  const policyPath = path.join(DATA_DIR, 'dial', 'inbound-policy.json');
  // Fallback line for events that don't name the number they arrived on. Each
  // event's actual destination (data.to) takes precedence, so the adapter
  // serves every number on the account, not just this one. Resolved lazily via
  // wiredLine() because the group doesn't exist yet when the adapter connects.
  const line = (): string => wiredLine();

  let setup: ChannelSetup | null = null;
  let connected = false;
  let watcher: fs.FSWatcher | null = null;
  let pollTimer: ReturnType<typeof setInterval> | null = null;
  let draining = false;
  const seen = new Map<string, number>();

  function seenBefore(id: string): boolean {
    const now = Date.now();
    for (const [k, ts] of seen) if (now - ts > DEDUP_TTL_MS) seen.delete(k);
    if (seen.has(id)) return true;
    seen.set(id, now);
    return false;
  }

  async function sendSms(to: string, body: string, from?: string): Promise<string | undefined> {
    // Send from the number the conversation is on (`from`); fall back to the
    // wired line. This is what lets one adapter serve multiple Dial numbers —
    // each reply goes out from the number the person actually texted.
    const fromNumber = from || wiredLine();
    let lastId: string | undefined;
    for (const chunk of body.length <= MAX_CHUNK ? [body] : chunkText(body, MAX_CHUNK)) {
      const sent = await client.sendMessage({
        to,
        body: chunk,
        ...(fromNumber ? { fromNumber } : {}),
      });
      lastId = sent?.id ?? lastId;
    }
    return lastId;
  }

  /**
   * Pairing interceptor: if an inbound SMS body is exactly a pending 6-digit
   * code, consume it — record the sender's number as a pairing candidate (owner
   * is granted only by the setup wizard, never from an inbound SMS), confirm by
   * SMS — and swallow the message so it never reaches an agent. Returns true
   * when consumed. Wrong codes are rate-limited per line; while a line is locked
   * even a correct code is refused and the message falls through to the normal
   * sender-policy path (dropped for unknown senders).
   */
  async function consumePairing(fromNumber: string, text: string, viaLine: string): Promise<boolean> {
    let result;
    try {
      result = await tryConsume({ text, fromNumber, viaLine });
    } catch (err) {
      log.warn('Dial: pairing consume failed', { err });
      return false;
    }
    if (result.rateLimited) {
      log.warn('Dial: pairing attempts rate-limited for line', { line: viaLine });
    }
    if (!result.record) return false;

    recordPairingCandidate(fromNumber);
    log.info('Dial: pairing code matched, recorded candidate — owner grant deferred to setup', {
      fromNumber,
      promotedToOwner: false,
    });
    try {
      await sendSms(fromNumber, 'Paired ✅ — your NanoClaw assistant is set up. Text me anytime.', viaLine);
    } catch (err) {
      log.warn('Dial: pairing confirmation SMS failed', { err });
    }
    return true;
  }

  /**
   * `is_group` is only written when the row is created, so a line registered
   * before its first message stays a DM — which collapses every correspondent
   * into one shared session. Runs per event, not just at startup: the line is
   * usually registered after the adapter connects. Also repairs older installs.
   */
  function ensureLinesAreGroups(): void {
    try {
      const wanted = inboundPolicy();
      for (const mg of getMessagingGroupsByChannel('dial')) {
        const updates: Partial<Pick<MessagingGroup, 'is_group' | 'unknown_sender_policy'>> = {};
        if (mg.is_group !== 1) updates.is_group = 1;
        if (mg.unknown_sender_policy !== wanted) updates.unknown_sender_policy = wanted;
        if (Object.keys(updates).length === 0) continue;
        updateMessagingGroup(mg.id, updates);
        log.info('Dial: reconciled line', { platformId: mg.platform_id, ...updates });
      }
    } catch (err) {
      log.warn('Dial: could not reconcile the line — correspondents may share one session', { err });
    }
  }

  /**
   * Who may text this line, chosen by the operator during setup and saved by
   * the add-dial skill. `strict` admits only the paired owner (and anyone
   * explicitly granted membership); `public` admits everyone.
   *
   * Defaults to `strict` when the file is missing: a phone number is guessable,
   * and an admitted sender gets a turn with an agent holding account-scoped
   * Dial credentials. Opting into `public` is the operator's call, not ours.
   */
  function inboundPolicy(): UnknownSenderPolicy {
    if (!fs.existsSync(policyPath)) return 'strict';
    try {
      const parsed = JSON.parse(fs.readFileSync(policyPath, 'utf8')) as { inboundAccess?: string };
      return parsed.inboundAccess === 'public' ? 'public' : 'strict';
    } catch (err) {
      log.warn('Dial: unreadable inbound-policy file, keeping the line owner-only', { policyPath, err });
      return 'strict';
    }
  }

  /**
   * The line this install is wired to. `config.fromNumber` comes from the auth
   * file, which `dial onboard` fills with the account's oldest number — not
   * necessarily the one setup wired — so prefer the registered group's own
   * platform_id and keep auth only as a pre-registration fallback.
   */
  function wiredLine(): string {
    try {
      const groups = getMessagingGroupsByChannel('dial');
      if (groups.length === 1) return groups[0].platform_id;
    } catch (err) {
      log.warn('Dial: could not resolve the wired line', { err });
    }
    return config.fromNumber;
  }

  /** The paired operator's E.164, or '' if the install has no Dial owner yet. */
  function ownerNumber(): string {
    try {
      const owner = getOwners().find((r) => r.user_id.startsWith('dial:'));
      return owner ? owner.user_id.slice('dial:'.length) : '';
    } catch (err) {
      log.warn('Dial: could not resolve the paired owner', { err });
      return '';
    }
  }

  /** Route one inbound event — SMS text and ended-call notifications. */
  async function routeEvent(env: DialEventEnvelope): Promise<void> {
    if (!setup) return;
    if (env.id && seenBefore(env.id)) return;
    const data = env.data ?? {};

    let peer = '';
    let text = '';
    // The Dial number this event arrived on (data.to for SMS; our own side of
    // a call). Used as the messaging group's platform_id so one adapter can
    // serve multiple Dial numbers — each number is its own group/line.
    let eventLine = '';
    if (env.type === 'message.received') {
      if (data.source && data.source !== 'external') return; // ignore Dial-synthesized test SMS
      peer = typeof data.from === 'string' ? data.from : '';
      eventLine = typeof data.to === 'string' ? data.to : '';
      text = typeof data.body === 'string' ? data.body : '';
      // Pairing codes are consumed before any agent sees them. Confirm from the
      // number the code was sent to (falls back to the account default).
      if (peer && (await consumePairing(peer, text, eventLine || line()))) return;
    } else if (env.type === 'call.ended') {
      const outbound = data.direction === 'outbound';
      const mine = outbound ? data.from : data.to;
      eventLine = typeof mine === 'string' ? mine : '';
      const callee = typeof data.to === 'string' ? data.to : '';

      if (outbound) {
        // The outcome belongs to the operator who asked for the call, not to
        // the person we dialled.
        peer = ownerNumber();
        if (!peer) {
          log.warn('Dial: outbound call ended but no paired owner to notify — dropping event', { callee });
          return;
        }
      } else {
        peer = typeof data.from === 'string' ? data.from : '';
      }

      const dur = typeof data.durationSeconds === 'number' ? `, ${data.durationSeconds}s` : '';
      const callId = typeof data.callId === 'string' ? data.callId : '';
      const transcript =
        data.transcriptAvailable && callId ? ` Run \`dial call get ${callId}\` for the transcript.` : '';
      const to = outbound && callee ? ` to ${callee}` : '';
      text = `[Voice call ${outbound ? 'outbound' : 'inbound'}${to} ${data.status ?? 'ended'}${data.canceled ? ' (canceled)' : ''}${dur}.${transcript}]`;
    } else {
      return;
    }
    if (!peer || !text) return;

    const id = [data.messageId, data.callId, env.id].find((v): v is string => typeof v === 'string' && !!v);
    // Public-line model: the Dial number itself is the messaging group; the peer
    // is the thread, so replies route back to them and every sender shares one
    // (public) wiring. `eventLine` is the number this event hit; fall back to the
    // account default when the event omits it (keeps single-number installs
    // unchanged).
    const activeLine = eventLine || line();
    const platformId = activeLine || peer;
    const threadId = activeLine ? peer : null;
    ensureLinesAreGroups();
    const msg: InboundMessage = {
      id: id ?? peer,
      kind: 'chat',
      content: { text, sender: peer, senderId: `dial:${peer}`, senderName: peer },
      isMention: true,
      // One line serves many people; a DM would collapse them into one session.
      isGroup: true,
      timestamp: env.createdAt || new Date().toISOString(),
    };
    void Promise.resolve(setup.onInbound(platformId, threadId, msg)).catch((err) =>
      log.error('Dial: onInbound failed', { peer, err }),
    );
    log.info('Dial inbound routed', { peer, type: env.type });
  }

  function processSpoolFile(file: string): void {
    const full = path.join(spoolDir, file);
    let raw: string;
    try {
      raw = fs.readFileSync(full, 'utf8');
    } catch {
      return; // already consumed by a concurrent tick
    }
    try {
      fs.unlinkSync(full);
    } catch {
      /* best-effort */
    }
    if (!raw.trim()) return;
    let env: DialEventEnvelope;
    try {
      env = JSON.parse(raw) as DialEventEnvelope;
    } catch (err) {
      log.warn('Dial: unparseable spooled event', { file, err });
      return;
    }
    void routeEvent(env).catch((err) => log.error('Dial: routeEvent failed', { err }));
  }

  /** Drain the spool directory once, in filename (roughly chronological) order. */
  function drainSpool(): void {
    if (draining) return;
    draining = true;
    try {
      for (const f of fs
        .readdirSync(spoolDir)
        .filter((f) => f.endsWith('.json'))
        .sort()) {
        processSpoolFile(f);
      }
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') log.debug('Dial: spool drain error', { err });
    } finally {
      draining = false;
    }
  }

  /**
   * Best-effort: write the handler script and register it as a Dial CLI command
   * target. Failures are logged, never thrown — the adapter keeps watching the
   * spool, and the wizard/skill can establish this out of band.
   */
  function ensureCommandTarget(): void {
    try {
      fs.mkdirSync(path.dirname(handlerPath), { recursive: true });
      fs.writeFileSync(handlerPath, handlerScript(spoolDir), { mode: 0o755 });
      fs.chmodSync(handlerPath, 0o755);
    } catch (err) {
      log.warn('Dial: could not write command-target handler', { handlerPath, err });
      return;
    }
    try {
      const listed = execFileSync(config.cliPath, ['local-target', 'list', '--json'], {
        encoding: 'utf8',
        timeout: 15_000,
      });
      if (!listed.includes(handlerPath)) {
        execFileSync(config.cliPath, ['local-target', 'add', 'cmd', handlerPath], { stdio: 'ignore', timeout: 15_000 });
        log.info('Dial: registered CLI command target', { handlerPath });
      }
    } catch (err) {
      log.warn(
        'Dial: could not register command target — check `dial` is on PATH (DIAL_CLI_PATH) and `dial listen install` has run',
        { err },
      );
    }
  }

  const adapter: ChannelAdapter = {
    name: 'dial',
    channelType: 'dial',
    supportsThreads: true,
    defaults: DIAL_DEFAULTS,

    async setup(cfg: ChannelSetup): Promise<void> {
      setup = cfg;
      ensureLinesAreGroups();
      fs.mkdirSync(spoolDir, { recursive: true });
      ensureCommandTarget();

      drainSpool(); // anything spooled while we were down
      try {
        watcher = fs.watch(spoolDir, () => drainSpool());
      } catch (err) {
        log.debug('Dial: fs.watch unavailable, relying on poll', { err });
      }
      pollTimer = setInterval(drainSpool, 2000); // fallback — fs.watch misses events on some mounts

      connected = true;
      log.info('Dial channel connected', { line: config.fromNumber || '(account default)' });
    },

    async teardown(): Promise<void> {
      connected = false;
      watcher?.close();
      watcher = null;
      if (pollTimer) clearInterval(pollTimer);
      pollTimer = null;
      log.info('Dial channel disconnected');
    },

    isConnected(): boolean {
      return connected;
    },

    async deliver(platformId: string, threadId: string | null, message: OutboundMessage): Promise<string | undefined> {
      const content = message.content as Record<string, unknown> | string | undefined;
      const text =
        typeof content === 'string'
          ? content
          : content && typeof content === 'object' && typeof content.text === 'string'
            ? content.text
            : '';
      if (!text) return undefined;

      // Public-line model: the correspondent is the thread. Reply to threadId;
      // platformId is the Dial line this conversation is on. Never text the
      // line's own number, and send the reply FROM that line so multi-number
      // installs answer from the number the person texted.
      const recipient = threadId || platformId;
      if (!recipient || recipient === platformId) {
        log.warn('Dial: no reply recipient (no thread) — dropping outbound', { platformId, threadId });
        return undefined;
      }
      try {
        return await sendSms(recipient, text, platformId);
      } catch (err) {
        log.error('Dial: sendMessage failed', { recipient, err });
        return undefined;
      }
    },
  };

  return adapter;
}

// ---------------------------------------------------------------------------
// Self-registration
// ---------------------------------------------------------------------------

registerChannelAdapter('dial', {
  factory: () => {
    // Credentials come from Dial's own auth file (written by `dial onboard`).
    const authFile = path.join(
      process.env.XDG_DATA_HOME || path.join(homedir(), '.local', 'share'),
      'dial',
      'auth.v1.json',
    );
    let apiKey = '';
    let fromNumber = '';
    try {
      const auth = JSON.parse(fs.readFileSync(authFile, 'utf8')) as { apiKey?: string; phoneNumber?: string };
      apiKey = auth.apiKey ?? '';
      fromNumber = auth.phoneNumber ?? '';
    } catch {
      /* no auth file — not signed in */
    }
    if (!apiKey) {
      log.debug('Dial: not signed in (run `dial signup` + `dial onboard`), skipping channel');
      return null;
    }

    const env = readEnvFile(['DIAL_CLI_PATH']);
    const cliPath = process.env.DIAL_CLI_PATH || env.DIAL_CLI_PATH || 'dial';
    return createDialAdapter({ apiKey, fromNumber, cliPath });
  },
  defaults: DIAL_DEFAULTS,
});
